MAINTENANCE: false
MAINTENANCE-KICK-MESSAGE: '&eMaintenance is enabled, come back later.'
MAINTENANCE-KICKINGAME-MESSAGE: '&eMaintenance was enabled, please come back later.'
MOTD: '&6Cool&ePVP Server'